apiVersion: v1
name: waypoint
appVersion: "0.1.5"
description: A Helm chart created for Hashicorp Waypoint server deployment by Fuchicorp
name: waypoint
version: 0.1.0
sources:
  - https://www.waypointproject.io/
  - https://github.com/fuchicorp/helm_charts/tree/master/stable/waypoint
maintainer:
  - name: Fuchicorp